Route101_Text_16D10E:: @ 816D10E
	.string "¡Socorro! ¡Ayuda!$"

Route101_Text_16D119:: @ 816D119
	.string "¡Oye! ¡Sí, tu!\n"
	.string "¡Ayúdame, por favor!\p"
	.string "¡Coge la POKé BALL!\n"
	.string "¡En mi MOCHILA!$"

Route101_Text_16D15E:: @ 816D15E
	.string "Pe-pero... ¡¿adónde vas?!\n"
	.string "¡¡¡No me dejes así!!!$"

Route101_Text_16D191:: @ 816D191
	.string "PROF. ABEDUL: Uf...\p"
	.string "Estaba en la zona de hierba alta\n"
	.string "estudiando POKéMON salvajes.\l"
	.string "cuando me atacó uno...\p"
	.string "Me has salvado.\n"
	.string "¡Muchísimas gracias!\p"
	.string "¡Anda!\p"
	.string "¡Si eres {PLAYER}{KUN}!\p"
	.string "Éste no es el lugar para charlas, así que\n"
	.string "vente conmigo a mi LABORATORIO\l"
	.string "POKéMON, ¿vale?$"

Route101_Text_16D25E:: @ 816D25E
	.string "Si tus POKéMON están cansados,\n"
	.string "llévalos a un CENTRO POKéMON.\p"
	.string "Hay un CENTRO POKéMON en PUEBLO\n"
	.string "ESCASO, muy cerca de aquí.$"

Route101_Text_16D2CB:: @ 816D2CB
	.string "Los POKéMON salvajes te atacarán\n"
	.string "en las zonas de hierba alta.\p"
	.string "Si quieres atrapar POKéMON, ve donde\n"
	.string "haya hierba alta y busca.$"

Route101_Text_16D349:: @ 816D349
	.string "RUTA 101\n"
	.string "{0x79} PUEBLO ESCASO$"
