LittlerootTown_BrendansHouse_2F_Text_17337E:: @ 817337E
	.string "POKéMON fully restored!\n"
	.string "Items ready, and... Huh?$"

LittlerootTown_BrendansHouse_2F_Text_1733AF:: @ 81733AF
	.string "¿Eh?\n"
	.string "¿Quién...? ¿Quién eres tú?\p"
	.string "Ah...\n"
	.string "Ya...\p"
	.string "Eres {PLAYER}{KUN}.\n"
	.string "Y te acabas de mudar.\p"
	.string "Mmm... Yo me llamo AURA.\n"
	.string "¡Encantada!\p"
	.string "Yo...\n"
	.string "sueño con hacerme amiga de miles\l"
	.string "de POKéMON de todo el mundo.\p"
	.string "He... oído algo sobre ti, {PLAYER}{KUN}. Me\n"
	.string "lo ha dicho mi padre, el PROF. ABEDUL.\p"
	.string "Tenía muchas ganas de que nos\n"
	.string "cayéramos bien e hiciéramos amistad.\p"
	.string "Qué tontería, ¿no?\n"
	.string "Si acabo de conocerte, {PLAYER}{KUN}...\p"
	.string "Ji, ji, ji...\p"
	.string "¡Ahí va! ¡Se me había olvidado!\p"
	.string "¡Tenía que ir a ayudar a mi padre a\n"
	.string "atrapar POKéMON salvajes!\p"
	.string "¡{PLAYER}{KUN}, nos vemos luego!$"

LittlerootTown_BrendansHouse_2F_Text_1735C9:: @ 81735C9
	.string "Mis POKéMON están curados...\n"
	.string "Tengo todos los objetos... y...$"

LittlerootTown_BrendansHouse_2F_Text_1735FC:: @ 81735FC
	.string "Hey!\n"
	.string "You...\p"
	.string "Who are you?\p"
	.string "Oh, you’re {PLAYER}, aren’t you?\n"
	.string "Moved in next door, right?\p"
	.string "I didn’t know that you’re a girl.\p"
	.string "Dad, PROF. BIRCH, said that our new\n"
	.string "next-door neighbor is a GYM LEADER’s\l"
	.string "kid, so I assumed you’d be a guy.\p"
	.string "My name’s BRENDAN.\n"
	.string "So, hi, neighbor!\p"
	.string "Huh? Hey, {PLAYER}, don’t you have\n"
	.string "a POKéMON?\p"
	.string "Do you want me to go catch you one?\p"
	.string "Aw, darn, I forgot...\p"
	.string "I’m supposed to go help my dad catch\n"
	.string "some wild POKéMON.\p"
	.string "Some other time, okay?$"

LittlerootTown_BrendansHouse_2F_Text_1737AE:: @ 81737AE
	.string "MAY: {PLAYER}{KUN}!\p"
	.string "I was just checking my POKéDEX.\p"
	.string "There’s still a lot of POKéMON that\n"
	.string "I’ve seen but haven’t caught.\p"
	.string "And there are many others that\n"
	.string "I think will evolve.\p"
	.string "I wonder where I should go catch\n"
	.string "some POKéMON next?$"

LittlerootTown_BrendansHouse_2F_Text_173883:: @ 8173883
	.string "MAY: I wonder where I should go catch\n"
	.string "some POKéMON next?\p"
	.string "Wouldn’t it be funny if we ran into each\n"
	.string "other, {PLAYER}{KUN}?$"

LittlerootTown_BrendansHouse_2F_Text_1738F2:: @ 81738F2
	.string "BRENDAN: Hey, it’s {PLAYER}.\p"
	.string "I was just checking out my POKéDEX.\p"
	.string "There are still many POKéMON that\n"
	.string "I need to catch, I know, but this\l"
	.string "is looking pretty good.\p"
	.string "Checking this POKéDEX out gives me\n"
	.string "the urge to hit the road again.$"

LittlerootTown_BrendansHouse_2F_Text_1739CC:: @ 81739CC
	.string "BRENDAN: I’m having a hard time deciding\n"
	.string "where I should catch POKéMON next.\p"
	.string "Hey, {PLAYER}, if I see you while I’m out\n"
	.string "catching POKéMON, I can pitch you a\l"
	.string "battle if you’d like.$"

UnknownString_8173A76: @ 8173A76
	.string "It’s lined with POKéMON picture books.$"
