LittlerootTown_BrendansHouse_1F_Text_1730C2:: @ 81730C2
LittlerootTown_MaysHouse_1F_Text_1730C2:: @ 81730C2
	.string "Hola. ¿Quién eres tú?\p"
	.string "Ah...\n"
	.string "Ya...\p"
	.string "¡Tú eres {PLAYER}{KUN} y te acabas de\n"
	.string "mudar aquí al lado! ¿Qué tal?\p"
	.string "Nuestro retoño tiene más o\n"
	.string "menos tu edad.\p"
	.string "Se ha emocionado tantísimo cuando\n"
	.string "ha sabido que venías a vivir aquí...\p"
	.string "Ahora está arriba, creo.$"

LittlerootTown_BrendansHouse_1F_Text_1731C6:: @ 81731C6
	.string "Nuestro retoño está arriba, creo.$"

LittlerootTown_BrendansHouse_1F_Text_1731E3:: @ 81731E3
	.string "¿Adónde ha ido mi marido?\n"
	.string "Justo cuando tú, {PLAYER}{KUN} has\l"
	.string "venido a vernos...\p"
	.string "Ese hombre no se está quieto ni atado\n"
	.string "a una mesa. Habrá ido al LABORATORIO.$"

LittlerootTown_BrendansHouse_1F_Text_173262:: @ 8173262
	.string "Oh, {RIVAL} ha ido no sé adónde.\p"
	.string "De tal palo, tal astilla.\n"
	.string "{RIVAL} es incapaz de quedarse\p"
	.string "en casa sin hacer nada.$"

LittlerootTown_BrendansHouse_1F_Text_1732B9:: @ 81732B9
	.string "I think it’s wonderful for people to\n"
	.string "travel with POKéMON.\p"
	.string "But you should go home every so often\n"
	.string "to let your mother know you’re okay.\p"
	.string "She might not say it, but I’m sure she\n"
	.string "worries about you, {PLAYER}{KUN}.$"
