LittlerootTown_BrendansHouse_2F_Text_172E18:: @ 8172E18
	.string "El reloj está parado...\p"
	.string "Será mejor ponerlo en hora.$"

LittlerootTown_BrendansHouse_2F_Text_172E4C:: @ 8172E4C
	.string "MAMÁ: {PLAYER}, ¿te gusta tu\n"
	.string "nuevo cuarto?\p"
	.string "Bien. Todo está colocado como debe ser.\p"
	.string "También han acabado con la mudanza de\n"
	.string "la planta baja.\p"
	.string "¡Este servicio de mudanzas POKéMON\n"
	.string "es de lo más eficaz!\p"
	.string "Oh, deberías comprobar que tienes\n"
	.string "todas tus cosas en la mesa.$"

UnknownString_8172F31: @ 8172F31
	.string "The bookshelf is lined entirely with\n"
	.string "books on POKéMON.\p"
	.string "It’s {PLAYER}’s prized collection.$"

UnknownString_8172F85: @ 8172F85
	.string "{PLAYER} encendió el PC.$"

LittlerootTown_BrendansHouse_2F_Text_172F9A:: @ 8172F9A
	.string "{PLAYER} abrió el cuaderno.\p"
	.string "REGLA AVENTURERA N.º 1\n"
	.string "Pulsa START para abrir el MENÚ.\p"
	.string "REGLA AVENTURERA N.º 2\n"
	.string "Elige GUARDAR para guardar la partida.\p"
	.string "Las demás páginas están en blanco...$"

UnknownString_817303D: @ 817303D
	.string "{PLAYER} miró más de cerca el mapa\n"
	.string "de la región de HOENN.$"

LittlerootTown_BrendansHouse_2F_Text_17306C:: @ 817306C
	.string "Es una consola Nintendo GameCube.\p"
	.string "Hay una consola Game Boy Advance\n"
	.string "conectada a ella que sirve de Mando.$"
