Route103_Text_16D57A:: @ 816D57A
	.string "AURA: Veamos... En la RUTA 103 puedes\n"
	.string "encontrar POKéMON como...$"

Route103_Text_16D5B6:: @ 816D5B6
	.string "¡Oh, hola, {PLAYER}{KUN}!\p"
	.string "Ya... Mi padre te ha regalado un\n"
	.string "POKéMON...\p"
	.string "Y ya que estamos aquí, podríamos\n"
	.string "echar un combate rapidito!\p"
	.string "Te voy a enseñar cómo entrenar\n"
	.string "POKéMON.$"

Route103_Text_16D65B:: @ 816D65B
	.string "Wow! That’s great!\n"
	.string "{PLAYER}{KUN}, you’re pretty good!$"

Route103_Text_16D688:: @ 816D688
	.string "AURA: Creo que ya entiendo por qué mi\n"
	.string "padre te tiene tanto aprecio.\p"
	.string "Por ejemplo, ese POKéMON que acabas\n"
	.string "de recibir, ya te quiere un montón.\p"
	.string "Se ve que puedes hacer amistad con\n"
	.string "los POKéMON muy fácilmente.\p"
	.string "Bien, volvamos al LABORATORIO.$"

Route103_Text_16D762:: @ 816D762
	.string "BRENDAN: Okay, so it’s this one and\n"
	.string "that one that live on ROUTE 103...$"

Route103_Text_16D7A9:: @ 816D7A9
	.string "Hey, it’s {PLAYER}!\p"
	.string "...Oh, yeah, Dad gave you a POKéMON.\p"
	.string "Since we’re here, how about a little\n"
	.string "battle?\p"
	.string "I’ll teach you what being a TRAINER’s\n"
	.string "about!$"

Route103_Text_16D836:: @ 816D836
	.string "Huh, {PLAYER}, you’re not too shabby.$"

Route103_Text_16D856:: @ 816D856
	.string "BRENDAN: I think I get it.\n"
	.string "I think I know why my dad has his eye\l"
	.string "out for you now.\p"
	.string "Look, your POKéMON already likes you,\n"
	.string "even though you just got it.\p"
	.string "{PLAYER}, I get the feeling that you\n"
	.string "could befriend any POKéMON with ease.\p"
	.string "We should head back to the LAB.$"

Route103_Text_16D950:: @ 816D950
	.string "Mi POKéMON está agotado...\n"
	.string "Debería haber traído una POCIÓN...$"

Route103_Text_16D996:: @ 816D996
	.string "If you cross the sea from here,\n"
	.string "it’ll be a shortcut to OLDALE TOWN.\p"
	.string "Fufufu, that’s useful, isn’t it?$"

Route103_Text_16D9FB:: @ 816D9FB
	.string "RUTA 103\n"
	.string "{0x7A} PUEBLO ESCASO$"
