OldaleTown_Text_16AEC0:: @ 816AEC0
	.string "Quiero descansar un ratito, así que\n"
	.string "voy a guardar mi partida.$"

OldaleTown_Text_16AEF2:: @ 816AEF2
	.string "¡Hola!\n"
	.string "Trabajo en la TIENDA POKéMON.\p"
	.string "¿Querrías venir conmigo?$"

OldaleTown_Text_16AF2F:: @ 816AF2F
	.string "Ésta es la TIENDA POKéMON.\n"
	.string "Se reconoce por el tejado azul.\p"
	.string "Vendemos de todo, incluso POKé BALLS\n"
	.string "para atrapar POKéMON.\p"
	.string "Mira, te voy a hacer un regalo como\n"
	.string "parte de nuestra promoción.$"

OldaleTown_Text_16AFE1:: @ 816AFE1
	.string "Puedes usar una POCIÓN en cualquier\n"
	.string "momento, así que a veces puede ser más\l"
	.string "útil que buscar un CENTRO POKéMON.$"

OldaleTown_Text_16B045:: @ 816B045
	.string "¡Nooooo! ¡No te muevas!\n"
	.string "¡Ni se te ocurra pisar aquí!\p"
	.string "Acabo de descubrir las huellas\n"
	.string "de un POKéMON raro.\p"
	.string "Espera hasta que termine de\n"
	.string "hacer mi bosquejo, ¿vale?$"

OldaleTown_Text_16B0CC:: @ 816B0CC
	.string "Acabo de descubrir las huellas\n"
	.string "de un POKéMON raro.\p"
	.string "Espera hasta que termine de\n"
	.string "hacer mi bosquejo, ¿vale?$"

OldaleTown_Text_16B12A:: @ 816B12A
	.string "Ya he acabado el bosquejo de las\n"
	.string "huellas de este POKéMON raro.\p"
	.string "Ya he acabado el bosquejo de las\n"
	.string "huellas de este POKéMON raro\p"
	.string "Y ahora me doy cuenta de que...\n"
	.string "eran mis propias huellas, snif...$"

OldaleTown_Text_16B196:: @ 816B196
	.string "AURA: ¡{PLAYER}{KUN}!\n"
	.string "¡Ven aquí, deprisa!\l"
	.string "¡Vamos al LABORATORIO!$"

OldaleTown_Text_16B1BE:: @ 816B1BE
	.string "BRUNO: I’m heading back to my dad’s\n"
	.string "LAB now.\l"
	.string "{PLAYER}, you should hustle back, too.$"

OldaleTown_Text_16B20E:: @ 816B20E
	.string "PUEBLO ESCASO\n"
	.string "“Donde nunca pasa nada”.$"
