LittlerootTown_BrendansHouse_1F_Text_172429:: @ 8172429
	.string "MAMÁ: ¿Ves, {PLAYER}?\n"
	.string "¿A que esto es muy bonito?$"

LittlerootTown_BrendansHouse_1F_Text_172453:: @ 8172453
	.string "Los POKéMON del servicio de mudanzas\n"
	.string "hacen todo el trabajo duro y además.\l"
	.string "recogen lo que ensucian. ¡Es perfecto!\p"
	.string "{PLAYER}, tu cuarto está arriba.\n"
	.string "¡Ve a verlo, cariño!\p"
	.string "PAPÁ te ha comprado un nuevo\n"
	.string "reloj para que recuerdes este día.\l"
	.string "No olvides ponerlo en hora.$"

LittlerootTown_BrendansHouse_1F_Text_172531:: @ 8172531
	.string "MOM: Well, {PLAYER}?\p"
	.string "Aren’t you interested in seeing your\n"
	.string "very own room?$"

LittlerootTown_BrendansHouse_1F_Text_172574:: @ 8172574
LittlerootTown_MaysHouse_1F_Text_172574:: @ 8172574
	.string "MOM: {PLAYER}.\p"
	.string "Go set the clock in your room, honey.$"

LittlerootTown_BrendansHouse_1F_Text_1725A3:: @ 81725A3
	.string "MAMÁ: ¡{PLAYER}, {PLAYER}!\n"
	.string "¡Ven! ¡Ven rápido!$"

LittlerootTown_BrendansHouse_1F_Text_1725C9:: @ 81725C9
LittlerootTown_MaysHouse_1F_Text_1725C9:: @ 81725C9
	.string "MAMÁ: ¡Mira! ¡El GIMNASIO de PETALIA!\n"
	.string "¡A ver si sale tu padre!$"

LittlerootTown_BrendansHouse_1F_Text_1725FE:: @ 81725FE
LittlerootTown_MaysHouse_1F_Text_1725FE:: @ 81725FE
	.string "MAMÁ: Pues no... Qué lástima...\p"
	.string "Creo que estaba hace nada y se\n"
	.string "acaba de ir. Mala suerte.$"

LittlerootTown_BrendansHouse_1F_Text_172644:: @ 8172644
LittlerootTown_MaysHouse_1F_Text_172644:: @ 8172644
	.string "Ah, si, una cosa.\n"
	.string "Uno de los amigos de tu padre vive aquí.\p"
	.string "Se llama PROF. ABEDUL.\p"
	.string "Vive aquí al lado. Creo que deberías ir\n"
	.string "a verlo y presentarte, cariño.$"

LittlerootTown_BrendansHouse_1F_Text_1726D2:: @ 81726D2
	.string "MAMÁ: ¡Hasta luego, cielo!$"

LittlerootTown_BrendansHouse_1F_Text_1726E7:: @ 81726E7
	.string "MAMÁ: ¿Has ido a presentarte\n"
	.string "al PROF. ABEDUL?$"

LittlerootTown_BrendansHouse_1F_Text_172717:: @ 8172717
	.string "MOM: How are you doing, {PLAYER}?\n"
	.string "You look a little tired.\p"
	.string "I think you should rest a bit.$"

LittlerootTown_BrendansHouse_1F_Text_17276B:: @ 817276B
	.string "MOM: Take care, honey!$"

LittlerootTown_BrendansHouse_1F_Text_172782:: @ 8172782
	.string "MOM: Oh? Did DAD give you that BADGE?\p"
	.string "Then here’s something from your MOM!$"

LittlerootTown_BrendansHouse_1F_Text_1727CD:: @ 81727CD
	.string "Don’t push yourself too hard, dear.\n"
	.string "You can always come home.\p"
	.string "Go for it, honey!$"

LittlerootTown_BrendansHouse_1F_Text_17281D:: @ 817281D
	.string "Gyao, gyao gyaoh...$"

LittlerootTown_BrendansHouse_1F_Text_172831:: @ 8172831
	.string "Gwagwah gwah...$"

LittlerootTown_BrendansHouse_1F_Text_172841:: @ 8172841
	.string "ENTREVISTADOR: Y, desde el GIMNASIO de\n"
	.string "PETALIA, nos despedimos de todos.$"

UnknownString_817288C: @ 817288C
	.string "Hay una peli en la tele.\p"
	.string "Dos hombres están bailando sobre el\n"
	.string "teclado de un piano de cola.\p"
	.string "Bueno, mejor dejo de ver la tele.$"

UnknownString_81728E3: @ 81728E3
	.string "It’s the instruction booklet for the\n"
	.string "RUNNING SHOES.\p"
	.string "“Press the B Button to run while\n"
	.string "wearing your RUNNING SHOES.\p"
	.string "“Lace up your RUNNING SHOES and hit\n"
	.string "the road running!”$"

LittlerootTown_BrendansHouse_1F_Text_17298B:: @ 817298B
	.string "DAD: Hm?\p"
	.string "Hey, it’s {PLAYER}!\p"
	.string "It’s been a while since I saw you,\n"
	.string "but you look...stronger, somehow.\p"
	.string "That’s the impression I get.\n"
	.string "But your old man hasn’t given up yet!\p"
	.string "Oh, yes, I have something for you.\n"
	.string "This came to you from someone named\l"
	.string "MR. BRINEY.$"

LittlerootTown_BrendansHouse_1F_Text_172A7D:: @ 8172A7D
	.string "DAD: Hm, a TICKET for a ferry?\p"
	.string "If I recall, there are ferry ports in\n"
	.string "SLATEPORT and LILYCOVE.\p"
	.string "{PLAYER}, if you have ambition as a\n"
	.string "TRAINER, go to the BATTLE TOWER.\p"
	.string "It should teach you that there is\n"
	.string "no end to a TRAINER’s chosen path.$"

LittlerootTown_BrendansHouse_1F_Text_172B5E:: @ 8172B5E
	.string "I’d better get back to PETALBURG GYM.\p"
	.string "MOM, thanks for looking after the house\n"
	.string "while I’m away.$"

LittlerootTown_BrendansHouse_1F_Text_172BBC:: @ 8172BBC
	.string "MOM: That DAD of yours...\p"
	.string "He comes home for the first time in a\n"
	.string "while, but all he talks about is POKéMON.\p"
	.string "He should relax and stay a little longer.$"

UnknownString_8172C50: @ 8172C50
	.string "We bring you a special news bulletin.\p"
	.string "We’ve received reports of a blue FLYING\n"
	.string "POKéMON in various HOENN locales.\p"
	.string "The identity of this POKéMON has not\n"
	.string "yet been determined.\p"
	.string "We now return you to your regular\n"
	.string "movie presentation.$"

UnknownString_8172D30: @ 8172D30
	.string "We bring you a special news bulletin.\p"
	.string "We’ve received reports of a red FLYING\n"
	.string "POKéMON in various HOENN locales.\p"
	.string "The identity of this POKéMON has not\n"
	.string "yet been determined.\p"
	.string "We now return you to your regular\n"
	.string "movie presentation.$"

UnknownString_8172E0F: @ 8172E0F
	.string "Gau gau!$"
