UnknownString_8173A9D: @ 8173A9D
	.string "POKéMON SPECIES & HABITATS...\n"
	.string "HUMAN & POKéMON COEXISTENCE...\l"
	.string "POKéMONOLOGY FOR BEGINNERS...\p"
	.string "It’s brimming with books written by\n"
	.string "PROF. BIRCH.$"

LittlerootTown_ProfessorBirchsLab_Text_173B29:: @ 8173B29
	.string "¿Cómo? ¿El PROF. ABEDUL?\p"
	.string "El PROFESOR ha ido a hacer un trabajo.\n"
	.string "de campo. Vamos, que no está.\p"
	.string "Déjame que e explique qué es un\n"
	.string "trabajo de campo.\p"
	.string "Se trata de estudiar las cosas en su\n"
	.string "entorno natural, como el campo o la\l"
	.string "montaña, en vez de en el laboratio.\p"
	.string "El PROFESOR no es de los que se quedan.\n"
	.string "pegados a la mesa. Él prefiere salir y\l"
	.string "experimentar cosas. No le basta con\l"
	.string "leer sobre ellas en los libros.$"

LittlerootTown_ProfessorBirchsLab_Text_173C88:: @ 8173C88
	.string "The PROF isn’t one for doing desk work.\n"
	.string "He’s the type of person who would\l"
	.string "rather go outside and experience\l"
	.string "things than read about them here.$"

LittlerootTown_ProfessorBirchsLab_Text_173D15:: @ 8173D15
	.string "El PROF. ABEDUL estudia los hábitats\n"
	.string "y distribución de los POKéMON.\p"
	.string "Al PROFESOR le gusta contar con la\n"
	.string "ayuda de {RIVAL}. Se quieren mucho.$"

LittlerootTown_ProfessorBirchsLab_Text_173D94:: @ 8173D94
	.string "PROF. ABEDUL: Pues sí, {PLAYER}{KUN}.\p"
	.string "He oído hablar mucho de ti a tu padre.\p"
	.string "Me ha dicho que todavía no tienes\n"
	.string "tu propio POKéMON.\p"
	.string "Pero por la forma en que luchaste\n"
	.string "antes, sabes cómo arreglártelas.\p"
	.string "Se nota que por tus venas corre la\n"
	.string "sangre de tu padre.\p"
	.string "Ah, y muchas gracias por salvarme.\n"
	.string "Querría darte el POKéMON que usaste\l"
	.string "antes como agradecimiento.\p"
	.string "¡{PLAYER} recibió a {STR_VAR_1}!$"

LittlerootTown_ProfessorBirchsLab_Text_173EF8:: @ 8173EF8
	.string "PROF. ABEDUL: Ya que estamos, ¿por qué\n"
	.string "no le pones un mote a tu {STR_VAR_1}?$"

LittlerootTown_ProfessorBirchsLab_Text_173F3D:: @ 8173F3D
	.string "PROF. ABEDUL: Si te esfuerzas mucho\n"
	.string "y ganas experiencia, llegarás a ser\l"
	.string "genial entrenando POKéMON.\p"
	.string "Mi retoño, {RIVAL}, está en la RUTA 103\n"
	.string "estudiando POKéMON.\p"
	.string "No creo sea mala idea que vayas\n"
	.string "a ver a {RIVAL}. ¿Qué piensas?$"

LittlerootTown_ProfessorBirchsLab_Text_174015:: @ 8174015
	.string "PROF. ABEDUL: ¡Estupendo!\n"
	.string "{RIVAL} se alegrará mucho.\p"
	.string "Dile a {RIVAL} que te enseñe lo que\n"
	.string "debe hacer todo ENTRENADOR.$"

LittlerootTown_ProfessorBirchsLab_Text_174075:: @ 8174075
	.string "PROF. ABEDUL: Vamos, no seas\n"
	.string "así... Deberíais conoceros...$"

LittlerootTown_ProfessorBirchsLab_Text_1740B4:: @ 81740B4
	.string "PROF. ABEDUL: {RIVAL} debería estar\n"
	.string "en algún lugar de la RUTA 103.\p"
	.string "Si tú o tus POKéMON os cansáis,\n"
	.string "id a descansar a casa.$"

LittlerootTown_ProfessorBirchsLab_Text_17411F:: @ 817411F
	.string "PROF. ABEDUL: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Me han dicho que has ganado tu\n"
	.string "primer combate. ¡Nada menos que\l"
	.string "contra {RIVAL}! ¡Muy bien!\p"
	.string "{RIVAL} me ha estado ayudando con mi\n"
	.string "investigación durante mucho tiempo.\p"
	.string "{RIVAL} tiene un largo historial\n"
	.string "entrenando POKéMON.\p"
	.string "Mira, {PLAYER}{KUN}, encargué esto para\n"
	.string "mi investigación, pero quiero que lo\l"
	.string "tengas tú. Es una POKéDEX.$"

LittlerootTown_ProfessorBirchsLab_Text_17422F:: @ 817422F
	.string "{PLAYER} recibió una POKéDEX!$"

LittlerootTown_ProfessorBirchsLab_Text_174248:: @ 8174248
	.string "PROF. ABEDUL: La POKéDEX es un aparato\n"
	.string "de alta tecnología que registra todos\l"
	.string "los POKéMON que avistas o atrapas.\p"
	.string "Mi retoño, {RIVAL}, no se separa de ella.\p"
	.string "Cada vez que atrapa un POKéMON raro\n"
	.string "y registras los datos en la POKéDEX,\l"
	.string "viene a verme allá donde esté para\l"
	.string "enseñármelo.$"

LittlerootTown_ProfessorBirchsLab_Text_17436C:: @ 817436C
	.string "PROF. ABEDUL: ¡Innumerables POKéMON\n"
	.string "te esperan!\p"
	.string "¡Y a mí me espera mi trabajo de campo!$"

LittlerootTown_ProfessorBirchsLab_Text_1743D4:: @ 81743D4
	.string "AURA: ¡Ahí va, {PLAYER}{KUN}!\n"
	.string "¡Ahora tú también tienes una POKéDEX!\p"
	.string "¡Qué guay! ¡Como la mía!\n"
	.string "¡Yo también tengo algo para ti!$"

LittlerootTown_ProfessorBirchsLab_Text_17443D:: @ 817443D
	.string "AURA: ¡Es divertidísimo atrapar un\n"
	.string "montón de POKéMON!\p"
	.string "Voy a rebuscar por todas partes\n"
	.string "porque quiero uno de cada.\p"
	.string "Si me encuentro con uno que me guste,\n"
	.string "¡lo atraparé con mis POKé BALLS!$"

LittlerootTown_ProfessorBirchsLab_Text_1744F0:: @ 81744F0
	.string "Oh? Your BAG’s full.$"

LittlerootTown_ProfessorBirchsLab_Text_174505:: @ 8174505
	.string "AURA: ¿Adónde puedo ir a buscar\n"
	.string "más POKéMON?$"

LittlerootTown_ProfessorBirchsLab_Text_17453C:: @ 817453C
	.string "BRENDAN: Huh...\n"
	.string "So you got a POKéDEX, too.\p"
	.string "Well then, here.\n"
	.string "I’ll give you this.$"

LittlerootTown_ProfessorBirchsLab_Text_17458C:: @ 817458C
	.string "BRENDAN: You know it’s more fun to\n"
	.string "have a whole bunch of POKéMON.\p"
	.string "I’m going to explore all over the place\n"
	.string "to find different POKéMON.\p"
	.string "If I find any cool POKéMON, you bet\n"
	.string "I’ll try to get them with POKé BALLS.$"

LittlerootTown_ProfessorBirchsLab_Text_17465B:: @ 817465B
	.string "Hey, your BAG’s full.$"

LittlerootTown_ProfessorBirchsLab_Text_174671:: @ 8174671
	.string "BRENDAN: Where should I look for\n"
	.string "POKéMON next...$"

LittlerootTown_ProfessorBirchsLab_Text_1746A2:: @ 81746A2
	.string "Es una máquina impresionante.\n"
	.string "El PROFESOR debe usarla para\l"
	.string "avanzar en su investigación.$"

LittlerootTown_ProfessorBirchsLab_Text_1746E7:: @ 81746E7
	.string "Es un PC que usan los científicos.\n"
	.string "Mejor no trasteo mucho por aquí.$"

LittlerootTown_ProfessorBirchsLab_Text_174724:: @ 8174724
	.string "Está repleta de libros sobre POKéMON.$"

LittlerootTown_ProfessorBirchsLab_Text_174748:: @ 8174748
	.string "Es un libro muy complicado.$"
