OldaleTown_Mart_Text_174A8A:: @ 8174A8A
	.string "El empleado dice que lo han vendido.\n"
	.string "todo.\p"
	.string "No puedo comprar ninguna POKé BALL$"

OldaleTown_Mart_Text_174ACB:: @ 8174ACB
	.string "¡Voy a comprar un buen montón de POKé\n"
	.string "BALLS para cazar cantidad POKéMON!$"

OldaleTown_Mart_Text_174B10:: @ 8174B10
	.string "Si dañan a un POKéMON, éste pierde PS,\n"
	.string "se debilita y no puede seguir luchando.\p"
	.string "Para evitar que se debilite, restaura\n"
	.string "sus PS con una POCIÓN.$"
