OldaleTown_PokemonCenter_1F_Text_1748D1:: @ 81748D1
	.string "Ese PC de la esquina es para el uso\n"
	.string "de cualquier ENTRENADOR POKéMON.\p"
	.string "Eso quiere decir que tú también lo\n"
	.string "puedes usar, claro.$"

OldaleTown_PokemonCenter_1F_Text_174945:: @ 8174945
	.string "¡Los CENTROS POKéMON son guays!\p"
	.string "Puedes usar sus servicios todas las\n"
	.string "veces que quieras y siempre es gratis.\l"
	.string "¡Es una pasada!$"

OldaleTown_PokemonCenter_1F_Text_1749C0:: @ 81749C0
	.string "Acabaron de construir el CLUB del CABLE\n"
	.string "POKéMON del segundo piso hace poco.\p"
	.string "Pero dijeron que aún están en\n"
	.string "reformas.$"

OldaleTown_PokemonCenter_1F_Text_174A2E:: @ 8174A2E
	.string "Acabaron de construir el CLUB del CABLE\n"
	.string "POKéMON del segundo piso hace poco.\p"
	.string "¡Vengo de intercambiar un POKéMON!$"
