LittlerootTown_Text_16A7C9:: @ 816A7C9
	.string "MAMÁ: ¡{PLAYER}, ya hemos llegado, cielo!\p"
	.string "Debe de ser agotador viajar en el camión\n"
	.string "de la mudanza con todos los muebles...\p"
	.string "Bueno, esto es VILLA RAÍZ.\p"
	.string "¿Qué? ¿Te gusta?\n"
	.string "¡Aquí es donde vamos a vivir!\p"
	.string "Es un lugar pintoresco, pero creo que\n"
	.string "se puede vivir muy a gusto aquí, ¿eh?\p"
	.string "¡Y además tienes tu propio cuarto!\n"
	.string "¡Entremos en casa!$"

LittlerootTown_Text_16A8EE:: @ 816A8EE
	.string "MAMÁ: ¡Espera, {PLAYER}!$"

LittlerootTown_Text_16A8FD:: @ 816A8FD
	.string "MAMÁ: ¡{PLAYER}, {PLAYER}! ¿Ya te has\n"
	.string "presentado al PROF. ABEDUL?\p"
	.string "Ooooh... ¡Qué POKéMON tan bonito!\n"
	.string "¿Te lo ha dado el PROFESOR? ¡Qué majo!\p"
	.string "Se ve que has salido a tu padre.\n"
	.string "¡Tienes mano con los POKéMON!\p"
	.string "Muy bie, tesoro. Si vas a irte de\n"
	.string "aventuras, toma estas DEPORTIVAS.\p"
	.string "¡Con ellas, más que correr, volarás!$"

LittlerootTown_Text_16AA32:: @ 816AA32
	.string "¡{PLAYER} se ha equipado las\n"
	.string "DEPORTIVAS!$"

LittlerootTown_Text_16AA5C:: @ 816AA5C
	.string "MAMÁ: {PLAYER}, estas zapatillas de\n"
	.string "deporte traen instrucciones y todo.\p"
	.string "“Pulsa el Botón B cuando lleves las\n"
	.string "DEPORTIVAS para salir pitando!\p"
	.string "“Ponte las DEPORTIVAS y empieza\n"
	.string "a correr por todas partes”.$"

LittlerootTown_Text_16AB10:: @ 816AB10
	.string "Ay...\n"
	.string "Cómo pasa el tiempo...\p"
	.string "Pensar que ya tienes tu propio\n"
	.string "POKéMON... Que contento\l"
	.string "se va a poner tu padre...\p"
	.string "Pero ten cuidado, ¿vale?\n"
	.string "Y pasa por casa cuando quieras.\p"
	.string "¡Adelante, cariño! ¡Atrápalos todos!$"

LittlerootTown_Text_16AC00:: @ 816AC00
	.string "¿Sabes que puedes guardar objetos\n"
	.string "y POKéMON en un PC?.\p"
	.string "¡La ciencia avanza que es una\n"
	.string "barbaridad!$"

LittlerootTown_Text_16AC56:: @ 816AC56
	.string "El PROF. ABEDUL se pasa los días metido\n"
	.string "en el LABORATORIO, pero a veces sale\l"
	.string "a investigar sobre el terrno.\p"
	.string "¿Cuándo se va a su casa, digo yo?...$"

LittlerootTown_Text_16ACEB:: @ 816ACEB
	.string "Si te metes en las zonas de hierba alta,\n"
	.string "encontrarás POKéMON salvajes.$"

LittlerootTown_Text_16AD3C:: @ 816AD3C
	.string "No es seguro salir por ahí si no\n"
	.string "vas con algún POKéMON.$"

LittlerootTown_Text_16AD82:: @ 816AD82
	.string "Alguien está gritando por ahí.\p"
	.string "¿Qué hago? ¿Qué hacemos?\n"
	.string "¡Alguien tiene que ayudarle!$"

LittlerootTown_Text_16ADF2:: @ 816ADF2
	.string "Uf, qué contento estoy de que fueras\n"
	.string "a rescatar al PROFESOR...$"

LittlerootTown_Text_16AE25:: @ 816AE25
	.string "¿Vas a atrapar POKéMON?\n"
	.string "¡Buena suerte!$"

LittlerootTown_Text_16AE50:: @ 816AE50
	.string "VILLA RAÍZ\n"
	.string "“Un pueblo poco colorido”.$"

LittlerootTown_Text_16AE87:: @ 816AE87
	.string "LABORATORIO POKéMON del PROF. ABEDUL$"

LittlerootTown_Text_16AEA1:: @ 816AEA1
	.string "CASA de {PLAYER}$"

LittlerootTown_Text_16AEAC:: @ 816AEAC
	.string "CASA del PROF. ABEDUL$"
